sudo: required

language: go

go:
 - 1.9
 - tip

services:
  - docker

matrix:
  allow_failures:
   - go: tip

  fast_finish: true

script:
  - sh scripts/test.sh "$TRAVIS_BUILD_DIR/compose-testing.yml"
