sudo: required

language: go

go:
 - 1.9
 - tip

services:
  - docker

matrix:
  allow_failures:
   - go: tip

  fast_finish: true

before_install:
  - docker-compose -f compose-testing.yml build

script:
  - docker-compose -f compose-testing.yml up -d postgres
  - docker-compose -f compose-testing.yml run go

after_script:
  - docker-compose -f compose-testing.yml down
