postgres:
  image: postgres:latest
  ports:
    - "5432"
  environment:
    - HOST=127.0.0.1
    - PORT=5432
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=dev
    - POSTGRES_DB=scoutingbackend

go:
  build: .
  links:
    - postgres:db
  ports:
    - "8080"
  environment:
    - ENVIRONMENT=dev
